[build]
  command = "DISABLE_ESLINT_PLUGIN=true npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  DISABLE_ESLINT_PLUGIN = "true"

# These redirects are handled by the Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Edge Functions aren't needed when using the Next.js plugin
# [functions]
#   node_bundler = "esbuild"