[build]
  command = "DISABLE_ESLINT_PLUGIN=true npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  NEXT_USE_NETLIFY_EDGE = "true"

# Add Next.js specific redirects to handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Explicitly handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200

# Enable Edge Functions
[functions]
  node_bundler = "esbuild"