[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Set the exact Python version
  NODE_VERSION = "22.x"
  PYTHON_VERSION = "3.13"