[build]
  command = "./setup-go.sh"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  GO_VERSION = "1.19"
  # Add Go binary location to PATH
  PATH = "/tmp/go/bin:${PATH}"